### ISSUE TITLE
main does not compile with Swift 6.3 on macOS

### ISSUE THREAD

**Issue by fabianfett** [apple/swift-collections#580]
Compile error:

```
/swift-collections/Sources/ContainersPreview/Extensions/TemporaryAllocation.swift:25:7: error: thrown expression type 'any Error' cannot be converted to error type 'E'
23 | ) throws(E) -> R {
24 | #if compiler(>=6.3)
25 |   try withUnsafeTemporaryAllocation(of: type, capacity: capacity, body)
   |       `- error: thrown expression type 'any Error' cannot be converted to error type 'E'
26 | #else
27 |   let r: Result<R, E> = withUnsafeTemporaryAllocation(
```

Swift version:
```
swift-driver version: 1.148.6 Apple Swift version 6.3 (swiftlang-6.3.0.122.3 clang-2100.0.122.2)
Target: arm64-apple-macosx26.0
```
