### ISSUE TITLE
missing _swift_initBorrow at launch on iOS 26.5

### ISSUE THREAD

**Issue by alexisbronchart** [apple/swift-collections#733]
After updating swift-collections from 1.6.0 to 1.7.0, my app aborts at launch on the iOS 26.5 simulator. It launches on iOS 27. The last version I used without this launch failure was 1.6.0.

### Information

- **Package version:** 1.7.0 (`a66de878e87ef5a3d5d390e0f6d9002aa5541a43`)
- **Platform version:** iOS 26.5, iPhone 17 Pro Max simulator
- **Swift version:**
  ```
  swift-driver version: 1.168.6 Apple Swift version 6.4 (swiftlang-6.4.0.34.1 clang-2100.3.34.1)
  Target: arm64-apple-macosx27.0.0
  ```
- **Xcode version:** 27.0 (27A266a)
- **iOS deployment target:** 18.6

### Checklist

- [ ] If possible, I've reproduced the issue using the `main` branch of this package.
- [x] I've searched for [existing GitHub issues](https://github.com/apple/swift-collections/issues).

### Steps to Reproduce

1. Add swift-collections 1.7.0 to an iOS app with a deployment target of 18.6.
2. Build the app with Xcode 27.0.
3. Launch it on the iOS 26.5 simulator.

I have not reduced this to a standalone sample yet. The app links `OrderedCollections`, and a transitive dependency links `DequeModule`.

### Expected behavior

The app launches on iOS 26.5.

### Actual behavior

The app aborts before reaching its entry point:

```text
dyld: Symbol not found: _swift_initBorrow
  Referenced from: NinePM.debug.dylib
  Expected in: /usr/lib/swift/libswiftCore.dylib
```

Inspecting the build artifacts with `nm` traces the undefined symbol to two swift-collections object files:

```text
InternalCollectionsUtilities/Optional+Extras.o
InternalCollectionsUtilities/BorrowingIteratorProtocol+Extras.o
```

This may be related to #732, which also concerns a runtime dependency introduced with 1.7.0, although that report involves a different missing library on macOS.

**Comment by pyrtsa** [comment]
We're seeing the same issue as well when building with Xcode 27 SDK (including the recent 27.1 and 27.2 betas) and trying to launch the app on an older simulator runtime.

**Comment by lorentey** [comment]
Hm; this appears to be a binary back-compatibility issue with the new `Ref` type in the 6.4 stdlib: the compiler emits a reference to the new runtime symbol `_swift_initBorrow` with strong linkage, preventing resulting binaries from loading on earlier OSes.

One workaround is to entirely avoid using `Ref`. Luckily the package is no longer using the helpers defined in the two source files that trigger this in `InternalCollectionsUtilities`, so removing them will likely resolve the issue.

**Comment by lorentey** [comment]
(Note: We're also internally tracking this in rdar://188247062.)

**Comment by upasch** [comment]
A standalone reproducer on **macOS**, in case it helps verify the fix. It has no app code and no other dependencies.

`Package.swift`:
```swift
// swift-tools-version:6.0
import PackageDescription
let package = Package(
    name: "Repro",
    platforms: [.macOS("26.0")],
    dependencies: [.package(url: "https://github.com/apple/swift-collections.git", exact: "1.7.0")],
    targets: [.executableTarget(name: "Repro", dependencies: [.product(name: "Collections", package: "swift-collections")])]
)
```
`Sources/Repro/main.swift`:
```swift
import Collections
var d = Deque<Int>()
d.append(1); d.prepend(0)
var o = OrderedSet<String>(["a", "b"])
o.append("c")
print(Array(d), Array(o))
```

Built with Xcode 27.0 (27A266a) and run on macOS 26.6.2 (25G83):

| build | `nm -m` for `_swift_initBorrow` | launch |
|---|---|---|
| 1.7.0, `swift build -c debug` | `(undefined) external … (from libswiftCore)` | `dyld: Symbol not found: _swift_initBorrow` |
| 1.7.0, `swift build -c release` | `(undefined) external … (from libswiftCore)` | same abort |
| 1.6.0, same package | no reference | runs |
| 1.7.0 with `-Xlinker -weak-lswiftCore` | `(undefined) weak external …` | runs |

The last row only confirms the diagnosis. It isn't a usable workaround, because it weak-links all of libswiftCore.

This also hits macOS apps that pull swift-collections in only transitively: in our case it comes through swift-transformers, and pinning 1.6.0 avoids it for now.

**Comment by lorentey** [comment]
The compiler-side fix is being prepared at https://github.com/swiftlang/swift/pull/92574. Meanwhile, I'll tag version 1.7.1 with a change that rips out the Ref mentions in InternalCollectionsUtilities for now, temporarily mitigating the issue on Swift 6.4.0.
