### PR TITLE
Work around another MergeModules crash

### LINKED ISSUE #56: DequeModule compilation error on Ubuntu
I'm trying to build a CLI tool in GitHub Actions with a dependency on this package. It's building fine on macOS but it fails to build on Ubuntu 20.04.2 LTS fails. I'm using fwal/setup-swift@v1 to install Swift on the ubuntu environment.
I apologise if this is not an issue on the package itself.

### Information

- **Package version:** Tried both 0.0.3 and the most recent commit c0549b6
- **Platform version:** Ubuntu 20.04.2 LTS
- **Swift version:** Swift version 5.4 (swift-5.4-RELEASE) | Target: x86_64-unknown-linux-gnu

### Checklist

- [x] If possible, I've reproduced the issue using the `main` branch of this package.
- [x] I've searched for [existing GitHub issues](https://github.com/apple/swift-collections/issues).

### Actual behavior
The compiler error is as follows:

```
gnu/debug/DequeModule.swiftmodule
2021-06-16T14:48:22.9117174Z <unknown>:0: error: fatal error encountered while reading from module 'DequeModule'; please submit a bug report (https://swift.org/contributing/#reporting-bugs) and include the project
2021-06-16T14:48:22.9119412Z <unknown>:0: note: module 'DequeModule' full misc version is '5.4(5.4)/Swift version 5.4 (swift-5.4-RELEASE)'
2021-06-16T14:48:22.9120239Z 
2021-06-16T14:48:22.9121042Z *** DESERIALIZATION FAILURE (please include this section in any bug report) ***
2021-06-16T14:48:22.9121888Z result not found
2021-06-16T14:48:22.9122743Z Cross-reference to module 'DequeModule'
2021-06-16T14:48:22.9123511Z ... Deque
2021-06-16T14:48:22.9124310Z ... in an extension in module 'DequeModule'
2021-06-16T14:48:22.9125028Z ... Element
2021-06-16T14:48:22.9125472Z 
2021-06-16T14:48:22.9126669Z Please submit a bug report (https://swift.org/contributing/#reporting-bugs) and include the project and the crash backtrace.
2021-06-16T14:48:22.9127715Z Stack dump:
2021-06-16T14:48:22.9174473Z 1.	Swift version 5.4 (swift-5.4-RELEASE)
2021-06-16T14:48:22.9175397Z 2.	While evaluating request ASTLoweringRequest(Lowering AST to SIL for module DequeModule)
2021-06-16T14:48:22.9176720Z 3.	While deserializing SIL function "$s11DequeModule0A0VAASERzlE6encode2toys7Encoder_p_tKF"
2021-06-16T14:48:22.9178025Z 4.	While reading from 'DequeModule'
2021-06-16T14:48:22.9179066Z 5.	While finishing conformance for protocol conformance to 'Sequence' (in module 'Swift') for type 'Deque<Element>'
```

[Full logs](https://gist.github.com/alexito4/6892f12e7d657a034db849e0dd10b84f)

### PR DESCRIPTION
**Pull request by lorentey**
The MergeModules phase in the compiler is [broken](https://bugs.swift.org/browse/SR-14448): it isn’t always able to correctly handle circular dependencies across source files, like the ones that keep organically popping up with Sequence/Collection conformances that are defined in separate files.

Such dependencies sometimes triggers a compiler crash, depending on some (unknown) environmental parameters.

Trying to manually find and eliminate these circular dependencies has not proved productive. Instead, roll all Collection conformances into a single, huge source file.

This PR also adds a new utility script that can be used to reproduce these issues by randomly shuffling filenames in a particular directory until one reordering triggers the problem. 

Resolves #56.

### Checklist
- [X] I've read the [Contribution Guidelines](/README.md#contributing-to-swift-collections)
- [X] My contributions are licensed under the [Swift license](/LICENSE.txt).
- [X] I've followed the coding style of the rest of the project.
- [ ] I've added tests covering all new code paths my change adds to the project (if appropriate).
- [ ] I've added benchmarks covering new functionality (if appropriate).
- [X] I've verified that my change does not break any existing tests or introduce unexplained benchmark regressions.
- [ ] I've updated the documentation if necessary.

### CODE REVIEW

**Comment by lorentey** [comment]
@swift-ci test

**Comment by lorentey** [comment]
@swift-ci test
