### ISSUE TITLE
DequeModule compilation error on Ubuntu

### ISSUE THREAD

**Issue by alexito4** [apple/swift-collections#56]
I'm trying to build a CLI tool in GitHub Actions with a dependency on this package. It's building fine on macOS but it fails to build on Ubuntu 20.04.2 LTS fails. I'm using fwal/setup-swift@v1 to install Swift on the ubuntu environment.
I apologise if this is not an issue on the package itself.

### Information

- **Package version:** Tried both 0.0.3 and the most recent commit c0549b6
- **Platform version:** Ubuntu 20.04.2 LTS
- **Swift version:** Swift version 5.4 (swift-5.4-RELEASE) | Target: x86_64-unknown-linux-gnu

### Checklist

- [x] If possible, I've reproduced the issue using the `main` branch of this package.
- [x] I've searched for [existing GitHub issues](https://github.com/apple/swift-collections/issues).

### Actual behavior
The compiler error is as follows:

```
gnu/debug/DequeModule.swiftmodule
2021-06-16T14:48:22.9117174Z <unknown>:0: error: fatal error encountered while reading from module 'DequeModule'; please submit a bug report (https://swift.org/contributing/#reporting-bugs) and include the project
2021-06-16T14:48:22.9119412Z <unknown>:0: note: module 'DequeModule' full misc version is '5.4(5.4)/Swift version 5.4 (swift-5.4-RELEASE)'
2021-06-16T14:48:22.9120239Z 
2021-06-16T14:48:22.9121042Z *** DESERIALIZATION FAILURE (please include this section in any bug report) ***
2021-06-16T14:48:22.9121888Z result not found
2021-06-16T14:48:22.9122743Z Cross-reference to module 'DequeModule'
2021-06-16T14:48:22.9123511Z ... Deque
2021-06-16T14:48:22.9124310Z ... in an extension in module 'DequeModule'
2021-06-16T14:48:22.9125028Z ... Element
2021-06-16T14:48:22.9125472Z 
2021-06-16T14:48:22.9126669Z Please submit a bug report (https://swift.org/contributing/#reporting-bugs) and include the project and the crash backtrace.
2021-06-16T14:48:22.9127715Z Stack dump:
2021-06-16T14:48:22.9174473Z 1.	Swift version 5.4 (swift-5.4-RELEASE)
2021-06-16T14:48:22.9175397Z 2.	While evaluating request ASTLoweringRequest(Lowering AST to SIL for module DequeModule)
2021-06-16T14:48:22.9176720Z 3.	While deserializing SIL function "$s11DequeModule0A0VAASERzlE6encode2toys7Encoder_p_tKF"
2021-06-16T14:48:22.9178025Z 4.	While reading from 'DequeModule'
2021-06-16T14:48:22.9179066Z 5.	While finishing conformance for protocol conformance to 'Sequence' (in module 'Swift') for type 'Deque<Element>'
```

[Full logs](https://gist.github.com/alexito4/6892f12e7d657a034db849e0dd10b84f)

**Comment by lorentey** [comment]
This looks like it might be the same issue as #7, but in `DequeModule` this time. 😩 If so, this is caused by an issue in MergeModules that only occurs on a subset of machines. 

This is usually triggered by a circular dependency between source files; while we're working to figure out the trigger, one workaround is to use a release build.

**Comment by lorentey** [comment]
Confirmed this is the same `MergeModules` issue; I can reproduce this by permuting the filenames in `Sources/DequeModule` and building the package with `-j 2`.

**Comment by lorentey** [comment]
I think the trigger is that `Deque`'s Sequence conformance (defined in `Deque+Sequence.swift`) mentions `Deque.count`, which is defined in `Deque+RandomAccessCollection.swift`, which file depends on `Deque`'s Sequence conformance. 

The Sequence conformance is exercised by the `encode(to:)` definition of `Deque+Codable.swift`, which is why this method appears in the crash report.

**Comment by lorentey** [comment]
Eliminating that particular circularity has uncovered another one:

```
1.	Apple Swift version 5.4 (swiftlang-1205.0.26.9 clang-1205.0.19.55)
2.	While evaluating request ASTLoweringRequest(Lowering AST to SIL for module DequeModule)
3.	While deserializing SIL function "$s11DequeModule0A0VyxGSlAASl7indices7IndicesQzvgTW"
4.	While reading from 'DequeModule'
5.	While finishing conformance for protocol conformance to 'RandomAccessCollection' (in module 'Swift') for type 'Deque<Element>'
```

This seems to be triggered by something about `indices`, which is inferred to be of type `Range<Int>`, but it isn't explicitly defined.

**Comment by lorentey** [comment]
Explicitly defining `indices` produces yet another variant:

```
1.	Apple Swift version 5.4 (swiftlang-1205.0.26.9 clang-1205.0.19.55)
2.	While evaluating request ASTLoweringRequest(Lowering AST to SIL for module DequeModule)
3.	While deserializing SIL function "$s11DequeModule0A0Vys5SliceVyACyxGGSnySiGcig"
4.	While reading from 'DequeModule'
5.	While finishing conformance for protocol conformance to 'Collection' (in module 'Swift') for type 'Deque<Element>'
```

The trigger is the slicing subscript getter, which is in fact explicitly defined.

```swift
  @inlinable
  public subscript(bounds: Range<Int>) -> Slice<Self> {
    get {
      precondition(bounds.lowerBound >= 0 && bounds.upperBound <= count,
                   "Invalid bounds")
      return Slice(base: self, bounds: bounds)
    }
    set(source) {
      precondition(bounds.lowerBound >= 0 && bounds.upperBound <= count,
                   "Invalid bounds")
      self.replaceSubrange(bounds, with: source)
    }
  }
```

As far as I can tell, this doesn't depend on anything but `count` and that's defined in the same file. Maybe it's the use of `Self` in the signature?

**Comment by lorentey** [comment]
> Maybe it's the use of `Self` in the signature?

Nope, removing that doesn't help.

**Comment by lorentey** [comment]
Killing that circular dependency results in an abort in `hash(into:)` which indicates there must still be issues with the Sequence conformance.

```
1.	Apple Swift version 5.4 (swiftlang-1205.0.26.9 clang-1205.0.19.55)
2.	While evaluating request ASTLoweringRequest(Lowering AST to SIL for module DequeModule)
3.	While deserializing SIL function "$s11DequeModule0A0VAASHRzlE4hash4intoys6HasherVz_tF"
4.	While reading from 'DequeModule'
5.	While finishing conformance for protocol conformance to 'Sequence' (in module 'Swift') for type 'Deque<Element>'
```

This is getting tiresome.

**Comment by lorentey** [comment]
`_copyToContiguousArray` still had references to `count`.

**Comment by lorentey** [comment]
```
1.	Apple Swift version 5.4 (swiftlang-1205.0.26.9 clang-1205.0.19.55)
2.	While evaluating request ASTLoweringRequest(Lowering AST to SIL for module DequeModule)
3.	While deserializing SIL function "$s11DequeModule0A0VyxGSlAASly11SubSequenceQzSny5IndexQzGcigTW"
4.	While reading from 'DequeModule'
5.	While finishing conformance for protocol conformance to 'Collection' (in module 'Swift') for type 'Deque<Element>'
```

(-_- )ﾉ⌒┻━┻

**Comment by lorentey** [comment]
I gave up in disgust and pulled every sequence/collection conformance into a single file, which seems to work around the compiler bug -- I've had >100 random permutations build correctly now.

**Comment by alexito4** [comment]
Thanks for the great effort on debugging this. I give this a try as soon as I can.
🤗
